import Head from 'next/head'
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub, } from "react-icons/ai";
import Image from 'next/image';
import ath from '../public/ath-wave.png';
// import Navbar from '../components/Navbar';
import Main from '../components/Main';
import About from '../components/About';
import Skills from '../components/Skills';
import Projects from '../components/Projects';
import Contact from '../components/Contact';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div className>
      <Head>
        <title>Athina Owoeye Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <Main />
          <About />
          <Skills />
          <Projects />
          <Contact />
          
    </div>
  );
}
