import Head from 'next/head'
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub, } from "react-icons/ai";
import Image from 'next/image';
import ath from '../public/ath-wave.png';
import Navbar from '../components/Navbar';
import Main from '../components/Main';
import About from '../components/About';
import Skills from '../components/Skills';
import Projects from '../components/Projects';
import Contact from '../components/Contact';

export default function Home() {
  return (
    <div className>
      <Head>
        <title>Athina Owoeye Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className="bg-white px-10">
        <section className="min-h-screen"> */}
          <Navbar />
          <Main />
          <About />
          <Skills />
          <Projects />
          <Contact />
         {/* <nav className="py-10 mb-12 flex justify-between">
           <h1 className="text-xl font-burtons">&lt;ATHINA CODEs /&gt;</h1>
           <ul className="flex items-center">
             <li>
               <BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
             </li>
             <li><a className=" bg-gradient-to-r from-violet-500 to-indigo-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
           </ul>
         </nav> */}
         {/* <div className="text-center p-10">
           <h2 className="text-5xl text-gray-700 py-2 font-medium my-8">Hi,I'm <span className=" text-indigo-600">Athina</span></h2>
           <h3 className="text-2xl text- gray-700 py-2">A Web Developer and designer.</h3>
           <p className="text-md text-gray-600 py-5 leading-7">I'm a front-end web developer specializing in building and designing scalable products with great user experience</p>
         </div>
         <div className="text-5xl flex justify-center gap-14
         py-3 text-gray-600">
           <AiFillLinkedin />
           <AiFillGithub />
         </div>
         <div className="relative mx-auto">
           <Image src={ath} />
         </div>
        </section>

      </main> */}
   </div>
  );
}
